name: Code Coverage

on: [push]

jobs:
  codecov:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Swift version
      run: swift --version
    - name: Gather code coverage
      run: swift test --enable-code-coverage
    - name: Generate report
      run: |
        xcrun llvm-cov show \
          .build/x86_64-apple-macosx/debug/swift-currencyPackageTests.xctest/Contents/MacOS/swift-currencyPackageTests \
          -instr-profile=".build/x86_64-apple-macosx/debug/codecov/default.profdata" \
          -ignore-filename-regex="(.build|Tests|ISOCurrencies)" > coverage.txt
    - name: Upload report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash) \
          -J "Currency" \
          -D ".build/debug"
