name: Code Coverage

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  codecov:
    if: ${{ !(github.event.pull_request.draft || false) }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Swift version
      run: swift --version
    - name: Run tests with code coverage
      run: swift test --enable-code-coverage
    - name: Upload code coverage
      uses: vapor/swift-codecov-action@v0.3
      with:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}
        build_parameters: -c debug
