name: 3rd Party Dependency Managers

on: pull_request

jobs:
  carthage:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check Carthage version
      run: carthage version
    - name: Run Carthage build
      run: carthage build --no-skip-current
  
  cocoapods:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint Podspec
      run: pod spec lint
